/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#091426",
        "accent": "#091426",
        "void": "#f7f9fb",
        "border": "#e2e8f0",
        "card": "#ffffff",
        "emerald": "#10b981",
        "rose": "#f43f5e",
        "on-tertiary-fixed": "#0d1c2d",
        "on-tertiary-container": "#8291a6",
        "background": "#f7f9fb",
        "on-tertiary": "#ffffff",
        "surface-dim": "#d8dadc",
        "secondary-fixed-dim": "#b7c8e1",
        "surface-container": "#eceef0",
        "secondary-container": "#d0e1fb",
        "tertiary-fixed-dim": "#b9c8de",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "on-secondary-container": "#54647a",
        "surface-variant": "#e0e3e5",
        "tertiary-fixed": "#d4e4fa",
        "surface": "#f7f9fb",
        "secondary-fixed": "#d3e4fe",
        "on-primary": "#ffffff",
        "inverse-surface": "#2d3133",
        "on-tertiary-fixed-variant": "#39485a",
        "on-secondary-fixed": "#0b1c30",
        "primary-fixed-dim": "#bcc7de",
        "on-surface-variant": "#45474c",
        "on-background": "#191c1e",
        "secondary": "#505f76",
        "surface-bright": "#f7f9fb",
        "surface-container-lowest": "#ffffff",
        "tertiary": "#061525",
        "outline-variant": "#c5c6cd",
        "on-primary-fixed": "#111c2d",
        "on-error": "#ffffff",
        "on-surface": "#191c1e",
        "inverse-on-surface": "#eff1f3",
        "error": "#ba1a1a",
        "surface-tint": "#545f73",
        "primary-fixed": "#d8e3fb",
        "outline": "#75777d",
        "surface-container-highest": "#e0e3e5",
        "surface-container-low": "#f2f4f6",
        "on-secondary-fixed-variant": "#38485d",
        "tertiary-container": "#1b2a3b",
        "on-primary-container": "#8590a6",
        "primary-container": "#1e293b",
        "error-container": "#ffdad6",
        "inverse-primary": "#bcc7de",
        "surface-container-high": "#e6e8ea",
        "on-primary-fixed-variant": "#3c475a"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xl": "64px",
        "gutter": "24px",
        "xs": "8px",
        "md": "24px",
        "sm": "16px",
        "lg": "40px",
        "base": "4px",
        "container_max": "1440px"
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "display": ["Inter"],
        "h2": ["Inter"],
        "label-caps": ["Inter"],
        "h1": ["Inter"],
        "h3": ["Inter"]
      },
      fontSize: {
        "body-lg": ["18px", {"lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400"}],
        "body-md": ["15px", {"lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400"}],
        "display": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "600"}],
        "h2": ["24px", {"lineHeight": "1.3", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.08em", "fontWeight": "600"}],
        "h1": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.03em", "fontWeight": "600"}],
        "h3": ["20px", {"lineHeight": "1.4", "letterSpacing": "-0.01em", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
}
